apiVersion: apps/v1
kind: Deployment
metadata:
  name: tech-challenge-2-deployment
  labels:
    app: tech-challenge-2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tech-challenge-2
  template:
    metadata:
      labels:
        app: tech-challenge-2
    spec:
      containers:
        - name: tech-challenge-2-container
          image: 801010559159.dkr.ecr.us-east-1.amazonaws.com/tech-challenge-2-repo:latest
          ports:
            - containerPort: 3000
